name: Publish EtherIP

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-check
  cancel-in-progress: true
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          repository: 'ornl-epics/etherip'
      - name: Setup Java
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4
        with:
          distribution: 'adopt'
          java-version: '11'
      - uses: whelk-io/maven-settings-xml-action@7802f6aec16c9098b4798ad1f1d8ac75198194bd # v3.0.0
        with:
          repositories: >
            [
              {
                  "id": "github",
                  "url": "https://maven.pkg.github.com/hivemq/hivemq-edge"
              }
            ]
          servers: >
            [
              {
                "id":"github",
                "username":"${{ github.actor }}",
                "password":"${{ secrets.GITHUB_TOKEN }}"
              }
            ]
      - name: Build and Publish
        run: mvn package deploy:deploy-file -DrepositoryId=github -Dfile=target/etherip-1.0.0.jar -DpomFile=pom.xml
